repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: bash -c ./process/check-sintax.sh
        language: system
        types: [ python ]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true