repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: bash -c "cd src && flake8 --count"
        language: system
        types: [ python ]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true